### PR TITLE
Contributing my registry rebuild recipe for Drupal

### PR DESCRIPTION
**Pull request by ElusiveMind**

### CODE REVIEW

**Comment by sk33lz** [comment]
This looks pretty solid, although we do include drush in all of our docker images, so in our docs we'd like to use the `drush @none dl registry_rebuild-7.x` and `drush cc drush` commands to enable registry_rebuild within the build instead. Please update those steps and I will merge this. Thanks again for your contributions to our docs!

**Review by jkaeser — CHANGES_REQUESTED** [review]
As per @sk33lz' comment, please update the "Rebuild the site registry" step to use drush. Otherwise, this looks good to me.

**Comment by ElusiveMind** [comment]
My rationale for this was in circumstances where the registry was in such a state where drush would not bootstrap and required the module .php file to be run manually from inside the repository. We had a circumstance of this where the site on database import would work until cache clear and then refuse to bootstrap even with drush cc all or drush rr. This was the only we found to resolve this issue. I can provide a real-world example of this if needed.

**Comment by sk33lz** [comment]
Let's just make 2 recipes then. I thought it was more just a preference, but if there is a use case, then let's :shipit:

**Comment by ElusiveMind** [comment]
No problem. And I'll document the use case for each in the recipe. I'll work on that likely later this week as I am traveling to TN as we speak.

**Comment by ElusiveMind** [comment]
Second recipe has been added - clarification of the differences between the two recipes has also been included.

**Review by jkaeser — APPROVED** [review]
Thank you for the updates, @ElusiveMind !

**Pull request merged**
