### PR TITLE
Writing docs for environment configuration options.

### PR DESCRIPTION
**Pull request by jkaeser**
Specifically the allowAccessWhileBuilding and basicAuth settings.

### CODE REVIEW

**Comment by jkaeser** [comment]
`basicAuth` seems to invalidate the `.probo.yaml` file.

**Comment by jkaeser** [comment]
@tortillaj Am I crazy or is the `basicAuth` config variable not working?

**Comment by tortillaj** [comment]
@jkaeser with respect to `basicAuth`, I don't think you're crazy. It's not working on [a rebuild I triggered](https://f2105b83-aa40-402e-87e4-ea32075cad4b.probo.build/). I think I'll try one of a different project type to get a repeat.

**Comment by tortillaj** [comment]
ping @tizzo ... I meant to bring this up earlier.  @jkaeser and I did some tests with `basicAuth`, and it works inconsistently. I was able to make it work once, but I think @jkaeser never did. We just did multiple builds of different types (Drupal, Jekyll, Wordpress). 

This PR has the `basicAuth` setting.

In probo: https://app.probo.ci/#/dashboard/build/f2105b83-aa40-402e-87e4-ea32075cad4b
The build: https://875d5a14-e690-4eb8-87f3-c79d9c6a46f7--pr-23.probo.build/

**Comment by jkaeser** [comment]
See the new docs at `/build/environment-configuration/`.

**Comment by tortillaj** [comment]
@tizzo when you have a chance, can you confirm that basic auth settings option? Both @jkaeser and I tried this and we both weren't able to make it work.

**Comment by jkaeser** [comment]
@tortillaj Guess we won't be getting the confirmation we were looking for 😢

**Comment by tizzo** [comment]
Get confirmation from someone else ;-)

**Comment by jkaeser** [comment]
@tizzo Lol let me complain!!!

**Comment by jkaeser** [comment]
Closing and moving work to #34

**Pull request closed without merging**
