### PR TITLE
Restructuring docs.

### PR DESCRIPTION
**Pull request by jkaeser**
The scope of this branch quickly grew, so I may push it up with a more fitting branch name later.

### CODE REVIEW

**Comment by jkaeser** [comment]
@tortillaj What do you think, should we move the Recipes page into the Build Configuration section, or should we leave it out on its own? I like it out since it has higher visibility, but it does make sense as part of the Build Config logical group.

**Comment by jkaeser** [comment]
Changes included in this PR:

- Added docs for ‘Build Controls’ e.g. pin builds, rebuilding environment
- Removed unnecessary pages, merging certain pages, reorganizing information
- Updated various pages with new information, removing outdated info/terminology, clarifying parts that were confusing
- Made the 'Getting Started’ page the front page
- Rearranged menu structure on the left
- Added border and padding to screenshot images

**Comment by tortillaj** [comment]
@jkaeser I like the recipes section outside too. Fire when ready!

**Comment by jkaeser** [comment]
@tortillaj  gif-star-wars-the-force-awakens-kylo-ren-favim com-3906708

**Comment by jkaeser** [comment]
51565ef3-7a3c-4118-89da-c752f7109451

**Pull request merged**
